# Generated by Django 5.2.7 on 2025-10-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_blog_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="categoty_name",
            new_name="category_name",
        ),
    ]
